name: churn
channels:
  - conda-forge
  - plotly
  - defaults
  - sebp
dependencies:
  - python=3.7
  - pandas=1.2.1
  - matplotlib=3.3.2
  - seaborn=0.11.1
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - py-xgboost=0.90
  - requests=2.25.1
  - kaggle=1.5.10
  - python-dotenv=0.15.0
  - lifelines=0.25.9
  - formulaic=0.2.3
  - scikit-survival=0.14.0
  - fastapi
  - uvicorn=0.19
